---
apiVersion: v1
kind: Service
metadata:
  name: product-api
spec:
  selector:
    app: product-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-api
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: conf
data:
  conf.json: |
    {
    "db_connection": "host=127.0.0.1 port=5432 user=postgres password=postgres dbname=product sslmode=disable",
    "bind_address": ":8080",
    "metrics_address": ":9102"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      serviceAccountName: product-api
      volumes:
        - name: config
          configMap:
            name: conf
      containers:
        - name: product-api
          image: hashicorpdemoapp/product-api:v0.0.20
          volumeMounts:
            - name: config
              mountPath: /app/conf.json
              subPath: conf.json
          ports:
            - containerPort: 8080
          env:
            - name: CONFIG_FILE
              value: /app/conf.json
